# Generated by Django 3.1.2 on 2021-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotifBatik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='gambar-batik/')),
                ('artikel', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
